(in-package :lem-user)
(use-package :lem-vi-mode)

;; AstroNvim like keybindings
(define-key *normal-keymap* "Space w" 'save-current-buffer)
(define-key *normal-keymap* "Space q" 'exit-lem)
(define-command open-init-file () ()
  (find-file "~/blazingly-fast/lem/init.lisp"))
(define-key *normal-keymap* "Space C" 'open-init-file)
(define-key *normal-keymap* "Space /" 'lem/language-mode:comment-or-uncomment-region)
(define-key *visual-keymap* "Space /" 'lem/language-mode:comment-or-uncomment-region)
(define-key *normal-keymap* "Space e" 'lem/filer::filer)
(define-key *normal-keymap* "Space o" 'next-window)
(define-key *normal-keymap* "Space b" 'lem/list-buffers:list-buffers)
(define-command kill-buffer-and-delete-window () ()
  (let ((buf (current-buffer)))
    (unless (one-window-p)
      (delete-active-window))
    (kill-buffer buf)))
(define-key *normal-keymap* "Space c" 'kill-buffer-and-delete-window)
(define-key *normal-keymap* "Space L" 'lem-lisp-mode:start-lisp-repl)
(define-key *normal-keymap* "Space ?" 'describe-key)
(define-key *normal-keymap* "] b" 'next-buffer)
(define-key *normal-keymap* "[ b" 'previous-buffer)
(define-key *normal-keymap* "] w" 'next-window)
(define-key *normal-keymap* "[ w" 'previous-window)
(define-key *normal-keymap* "Space l f" 'format-current-buffer)
(define-key *normal-keymap* "g d" 'lem/language-mode:find-definitions)
(define-key *normal-keymap* "g Backspace" 'lem/language-mode:pop-definition-stack)

;; Remove paredit bindings that conflict with vi motions
(undefine-key lem-paredit-mode:*paredit-mode-keymap* ")")
(undefine-key lem-paredit-mode:*paredit-mode-keymap* "(")
(undefine-key lem-paredit-mode:*paredit-mode-keymap* "[")
(undefine-key lem-paredit-mode:*paredit-mode-keymap* "]")
(undefine-key lem-paredit-mode:*paredit-mode-keymap* "{")
(undefine-key lem-paredit-mode:*paredit-mode-keymap* "}")

;; Re-add them only in vi insert mode where they make sense
(define-key lem-vi-mode:*insert-keymap* ")" 'lem-paredit-mode:paredit-close-parenthesis)
(define-key lem-vi-mode:*insert-keymap* "(" 'lem-paredit-mode:paredit-insert-paren)
(define-key lem-vi-mode:*insert-keymap* "[" 'lem-paredit-mode:paredit-insert-bracket)
(define-key lem-vi-mode:*insert-keymap* "]" 'lem-paredit-mode:paredit-close-bracket)
(define-key lem-vi-mode:*insert-keymap* "{" 'lem-paredit-mode:paredit-insert-brace)
(define-key lem-vi-mode:*insert-keymap* "}" 'lem-paredit-mode:paredit-close-brace)
