name: Deploy IntelliJ plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle build
        run: |
          cd utils/intellij-plugin
          chmod +x ./gradlew
          ./gradlew buildPlugin
          ./gradlew nodeSetup
          ./gradlew yarn
          ./gradlew yarn_build
      - name: Commit new release
        env:
          INTELLIJ_DEPLOY: ${{ secrets.INTELLIJ_DEPLOY }}
        run: |
          cd utils/intellij-plugin
          VERSION=`./gradlew yarn_bump`
          ./gradlew publishPlugin
          cd ../../
          git config --global user.name 'Shakhzod Kudratov'
          git config --global user.email 'shakhzodkudratov@gmail.com'
          git status
          git add .
          git commit -m "releasing $VERSION"
          git push
          git tag $VERSION
