name: Deploy IntelliJ plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle build
        run: |
          chmod +x ./utils/intellij-plugin/gradlew
          alias gradleww=./utils/intellij-plugin/gradlew
          gradleww buildPlugin
          gradleww nodeSetup
          gradleww yarn
          gradleww yarn_build
      - name: Commit new release
        env:
          INTELLIJ_DEPLOY: ${{ secrets.INTELLIJ_DEPLOY }}
        run: |
          alias gradleww=./utils/intellij-plugin/gradlew
          VERSION=`gradlew yarn_bump`
          gradleww publishPlugin
          git config --global user.name 'Shakhzod Kudratov'
          git config --global user.email 'shakhzodkudratov@gmail.com'
          git status
          git add .
          git commit -m "Releasing"
          git push
        #git tag $VERSION
