name: Deploy IntelliJ plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle build
        run: |
          chmod +x ./utils/intellij-plugin/gradlew
          ./utils/intellij-plugin/gradlew buildPlugin
          ./utils/intellij-plugin/gradlew nodeSetup
          ./utils/intellij-plugin/gradlew yarn
          ./utils/intellij-plugin/gradlew yarn_build
      - name: Commit new release
        env:
          INTELLIJ_DEPLOY: ${{ secrets.INTELLIJ_DEPLOY }}
        run: |
          VERSION=`./utils/intellij-plugin/gradlew yarn_bump`
          ./utils/intellij-plugin/gradlew publishPlugin
          git config --global user.name 'Shakhzod Kudratov'
          git config --global user.email 'shakhzodkudratov@gmail.com'
          git status
          git add .
          git commit -m "Releasing"
          git push
        #git tag $VERSION
