name: Build and verify IntelliJ plugin

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle build and verify
        run: |
          chmod +x ./utils/intellij-plugin/gradlew
          ./utils/intellij-plugin/gradlew buildPlugin
          ./utils/intellij-plugin/gradlew verifyPlugin
