name: Build and verify IntelliJ plugin

on:
  push:
    paths:
      - utils/intellij-plugin/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: intellij-plugin
    steps:
      - uses: actions/checkout@v2
      - name: Gradle build and verify
        run: |
          cd utils/intellij-plugin
          chmod +x ./gradlew
          ./gradlew buildPlugin
          ./gradlew verifyPlugin
